project_id = "aezqxhlogcvvfckhiyfl"

[functions.connect-email]
verify_jwt = false

[functions.email-oauth-callback]
verify_jwt = false

[functions.sync-emails]
verify_jwt = true

[functions.parse-emails]
verify_jwt = true

[functions.categorize-document]
verify_jwt = true

[functions.chat-assistant]
verify_jwt = true

[functions.generate-daily-focus]
verify_jwt = true

[functions.notifications-check]
verify_jwt = false
